
application: orangepekoepress
version: 2
runtime: python
api_version: 1


handlers:

- url: /static
  static_dir: static

- url: /admin.*
  script: main.py
  login: required
  secure: always

- url: /home.*
  script: main.py
  login: required

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /_ereporter/.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: .*
  script: main.py
